### ISSUE TITLE
Read config.yaml at startup

### ISSUE THREAD

**Issue by bpa** [bpa/tables#14]
Should contain:
```yaml
secret: site's secret
plugins:
  - name: name of plugin #will be used to find on the file system
    config1: specific to plugin
```
